### PR TITLE
Add `MxMiniaudio` wrapper to fix resource issues

### LINKED ISSUE #116: Fix incorrect resource use of miniaudio objects
https://github.com/isledecomp/isle-portable/pull/82#discussion_r2094641755

### PR DESCRIPTION
**Pull request by foxtacles**
Close #116

### CODE REVIEW

File: LEGO1/omni/include/mxminiaudio.h [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+	T* operator*()
+	{
+		assert(m_initialized);
+		if (m_initialized) {
+			return &m_object;
+		}
+
+		return nullptr;
+	}
```
Comment (madebr) [inline LEGO1/omni/include/mxminiaudio.h]:
```suggestion
	operator T*() {
		if (!m_initialized) {
			return nullptr;
		}
		return &m_object;
	}
```

File: LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp [hunk 2]
```diff
@@ -40,7 +40,7 @@ void Lego3DWavePresenter::StartingTickle()
 
 	MxWavePresenter::StartingTickle();
 
-	if (ma_sound_get_engine(&(MxWavePresenter::m_sound))) {
+	if (ma_sound_get_engine(*(MxWavePresenter::m_sound))) {
```
Comment (madebr) [inline LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp]:
```suggestion
	if (ma_sound_get_engine(static_cast<ma_sound*>(MxWavePresenter::m_sound))) {
```

File: LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp [hunk 3]
```diff
@@ -49,7 +49,7 @@ void Lego3DWavePresenter::StartingTickle()
 			m_compositePresenter->GetAction()->GetExtra(extraLength, buff);
 		}
 
-		if (m_sound.Create(&(MxWavePresenter::m_sound), buff, m_volume) != SUCCESS) {
+		if (m_sound.Create(*(MxWavePresenter::m_sound), buff, m_volume) != SUCCESS) {
```
Comment (madebr) [inline LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp]:
```suggestion
		if (m_sound.Create(static_cast<ma_sound*>(MxWavePresenter::m_sound), buff, m_volume) != SUCCESS) {
```

File: LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp [hunk 4]
```diff
@@ -60,5 +60,5 @@ void Lego3DWavePresenter::StartingTickle()
 void Lego3DWavePresenter::StreamingTickle()
 {
 	MxWavePresenter::StreamingTickle();
-	m_sound.UpdatePosition(&(MxWavePresenter::m_sound));
+	m_sound.UpdatePosition(*(MxWavePresenter::m_sound));
```
Comment (madebr) [inline LEGO1/lego/legoomni/src/audio/lego3dwavepresenter.cpp]:
```suggestion
	m_sound.UpdatePosition(static_cast<ma_sound*>(MxWavePresenter::m_sound));
```

File: LEGO1/omni/include/mxsoundmanager.h [hunk 5]
```diff
@@ -22,7 +22,7 @@ class MxSoundManager : public MxAudioManager {
 	virtual void Pause();                                                // vtable+0x34
 	virtual void Resume();                                               // vtable+0x38
 
-	ma_engine* GetEngine() { return &m_engine; }
+	ma_engine* GetEngine() { return *m_engine; }
```
Comment (madebr) [inline LEGO1/omni/include/mxsoundmanager.h]:
```suggestion
	ma_engine* GetEngine() { return static_cast<ma_engine *>(m_engine); }
```

File: LEGO1/omni/src/audio/mxsoundmanager.cpp [hunk 6]
```diff
@@ -88,15 +88,15 @@ MxResult MxSoundManager::Create(MxU32 p_frequencyMS, MxBool p_createThread)
...
 
-	if (ma_engine_init(&engineConfig, &m_engine) != MA_SUCCESS) {
+	if (m_engine.Init(ma_engine_init, &engineConfig) != MA_SUCCESS) {
 		goto done;
 	}
 
 	SDL_AudioSpec spec;
 	SDL_zero(spec);
-	spec.freq = ma_engine_get_sample_rate(&m_engine);
+	spec.freq = ma_engine_get_sample_rate(*m_engine);
```
Comment (madebr) [inline LEGO1/omni/src/audio/mxsoundmanager.cpp]:
```suggestion
	spec.freq = ma_engine_get_sample_rate(static_Cast<ma_engine*>(m_engine));
```

File: LEGO1/omni/include/mxminiaudio.h [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+
+	T* operator->()
+	{
+		assert(m_initialized);
+		if (m_initialized) {
+			return &m_object;
+		}
+
+		return nullptr;
+	}
```
Comment (madebr) [inline LEGO1/omni/include/mxminiaudio.h:45]: Do you still need this operator?
A normal `->` would return a `T` reference, but this again allows abuse. So perhaps better to remove it?
```suggestion
	T& operator->()
	{
		assert(m_initialized);
		return m_object;
	}
```

Comment (foxtacles) [reply LEGO1/omni/include/mxminiaudio.h:45]: We need it in a few places:

image

Comment (madebr) [reply LEGO1/omni/include/mxminiaudio.h:45]: Awesome! Merge this sh*t then :)

**Review by madebr — APPROVED** [review]
