### PR TITLE
Fix clear screen on buffered devices

### LINKED ISSUE #465: Flickering on credits screen
When using the OpenGL ES 2.0 or 1.1 HAL rendering device, the background of the credits screen flashes. I suspect this is to do with the credits screen not being built for higher framerates. I am on Endeavour OS (based on Arch Linux) on Wayland with an Nvidia GPU and 575.64 drivers. This happens both in fullscreen and in windowed mode.

Note: Do not watch the video if you are prone to seizures from flashing lights.

https://github.com/user-attachments/assets/ac81a2e2-a0d6-4c9c-a27c-f31f93cefca0

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #465

### CODE REVIEW

File: LEGO1/omni/src/video/mxdisplaysurface.cpp [hunk 1]
```diff
@@ -52,7 +52,7 @@ void MxDisplaySurface::ClearScreen()
 	DDSURFACEDESC desc;
 
 	if (!m_videoParam.Flags().GetFlipSurfaces()) {
-		backBuffers = 1;
+		backBuffers = 2;
```
Comment (foxtacles) [inline LEGO1/omni/src/video/mxdisplaysurface.cpp:55]: Could you explain this? How will this make a difference in the loop below?

Comment (AJenbo) [reply LEGO1/omni/src/video/mxdisplaysurface.cpp:55]: clearing one buffer is not enough on double buffered systems.

Comment (foxtacles) [reply LEGO1/omni/src/video/mxdisplaysurface.cpp:55]: Right, it's just confusing because `i` isn't being used in the loop logic. So I'm wondering what exactly happens.

**Review by foxtacles — APPROVED** [review]
