### PR TITLE
Fix mouse clicks in registration book

### LINKED ISSUE #109: Entering a name in the registration book by clicking the letters does nothing
It works fine in the decomp

### PR DESCRIPTION
**Pull request by madebr**
Fixes #109

### CODE REVIEW

File: LEGO1/lego/legoomni/src/worlds/registrationbook.cpp [hunk 1]
```diff
@@ -223,11 +223,14 @@ MxLong RegistrationBook::HandleKeyPress(SDL_Keycode p_key)
 // FUNCTION: LEGO1 0x100774a0
 MxLong RegistrationBook::HandleControl(LegoControlManagerNotificationParam& p_param)
 {
-	MxS16 unk0x28 = p_param.m_unk0x28;
+	// [1, 26]: alphabet
+	// 27: backspace
+	// 28: go back to information center
+	MxS16 buttonId = p_param.m_unk0x28;
```
Comment (foxtacles) [inline LEGO1/lego/legoomni/src/worlds/registrationbook.cpp:229]: can you share the naming improvement with the decimp? thank you

**Review by foxtacles — APPROVED** [review]

**Comment by AJenbo** [comment]
nice :)
