### PR TITLE
Get the game working on 64bit systems

### LINKED ISSUE #118: Isle fails to launch (crashes with `terminate called after throwing an instance of 'std::bad_alloc'`)
I am interesting in helping with this project, however I cannot test any of my changes, because Isle crashes with `terminate called after throwing an instance of 'std::bad_alloc'`. 

With ASAN and UBSAN I get:
```
=================================================================
==427305==ERROR: AddressSanitizer: requested allocation size 0x2e65636166676f65 (0x2e65636166677f68 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 0x7f0ce60f58d8 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98
    #1 0x7f0ce2e4949e in LegoTexturePresenter::Read(MxDSChunk&) (liblego1.so+0x2e4949e) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #2 0x7f0ce2be2205 in LegoWorldPresenter::LoadWorld(char*, LegoWorld*) (liblego1.so+0x2be2205) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #3 0x7f0ce2bea7d0 in LegoWorldPresenter::ParseExtra() (liblego1.so+0x2bea7d0) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #4 0x7f0ce2be0039 in LegoWorldPresenter::ReadyTickle() (liblego1.so+0x2be0039) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #5 0x7f0ce2593685 in MxPresenter::Tickle() (liblego1.so+0x2593685) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #6 0x7f0ce2e5f6f7 in LegoVideoManager::Tickle() (liblego1.so+0x2e5f6f7) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #7 0x7f0ce25a10e7 in MxTickleManager::Tickle() (liblego1.so+0x25a10e7) (BuildId: 10555f5abea8f1c4d87dc05694ddae06a43a6a05)
    #8 0x558aafc73aea in IsleApp::Tick() (/home/charlotte/git/isle-portable/build/isle+0x29aea) (BuildId: cab59e21e2f3ddb8991abff591aa3334ad757630)
    #9 0x558aafc6b113 in SDL_AppIterate (/home/charlotte/git/isle-portable/build/isle+0x21113) (BuildId: cab59e21e2f3ddb8991abff591aa3334ad757630)
    #10 0x7f0cdfcb3bf3 in SDL_IterateMainCallbacks (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0xb3bf3) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #11 0x7f0cdff22a3c in GenericIterateMainCallbacks (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0x322a3c) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #12 0x7f0cdff22b26 in SDL_EnterAppMainCallbacks_REAL (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0x322b26) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #13 0x7f0cdfc6fc4c in SDL_EnterAppMainCallbacks (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0x6fc4c) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #14 0x558aafc66a85 in SDL_main (/home/charlotte/git/isle-portable/build/isle+0x1ca85) (BuildId: cab59e21e2f3ddb8991abff591aa3334ad757630)
    #15 0x7f0cdfcb3cb9 in SDL_RunApp_REAL (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0xb3cb9) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #16 0x7f0cdfc67fed in SDL_RunApp_DEFAULT (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0x67fed) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #17 0x7f0cdfc74cc1 in SDL_RunApp (/home/charlotte/git/isle-portable/build/_deps/sdl3-build/libSDL3.so.0+0x74cc1) (BuildId: e603358849c16e4a9a2152b7737f3ed73bddb50d)
    #18 0x558aafc66ab0 in main (/home/charlotte/git/isle-portable/build/isle+0x1cab0) (BuildId: cab59e21e2f3ddb8991abff591aa3334ad757630)
    #19 0x7f0cdee33ca7  (/lib/x86_64-linux-gnu/libc.so.6+0x29ca7) (BuildId: cad07c44cacc6eb6db9097846504903149d0e1b6)

==427305==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: allocation-size-too-big ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98 in operator new[](unsigned long)
==427305==ABORTIN
```

I tried using the build from actions (I dunno, maybe it would make a difference) and it instead crashes because it cant find a usable audio device.
I did also get these warnings during compiling if it means anything:
```
-- libvorbisfile not found. miniaudio_libvorbis will be excluded.
-- libopusfile not found. miniaudio_libopus will be excluded.
-- SDL2 not found. SDL2 examples will be excluded.
-- SteamAudio not found. miniaudio_engine_steamaudio will be excluded.
```

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #118

This gets the game working on 64bit Linux. I simply replaced all instances of `long` with `int` except for the two places where we get the video size from libsmacker which uses `long`.

This should only have a "negative" effect when targeting 16bit systems, which isn't easy in the first place. If that becomes relevant then probably you should go over the src and change to more sane types like `std::uint32_t` where needed..

### CODE REVIEW

File: LEGO1/omni/include/mxtypes.h [hunk 1]
```diff
@@ -1,34 +1,21 @@
 #ifndef MXTYPES_H
 #define MXTYPES_H
 
+#include <cstdint>
```
Comment (foxtacles) [inline LEGO1/omni/include/mxtypes.h:4]: Let's use the C style stint.h header for consistency

File: LEGO1/lego/sources/misc/legotypes.h [hunk 2]
```diff
@@ -32,8 +32,8 @@ typedef char LegoS8;
 typedef unsigned char LegoU8;
 typedef short LegoS16;
 typedef unsigned short LegoU16;
-typedef long LegoS32;
-typedef unsigned long LegoU32;
+typedef int LegoS32;
+typedef unsigned int LegoU32;
```
Comment (madebr) [inline LEGO1/lego/sources/misc/legotypes.h:36]: Let's add a bunch of static asserts at the bottom of this file for all custom Lego types.

File: LEGO1/omni/include/mxtypes.h [hunk 3]
```diff
@@ -1,34 +1,21 @@
...
 typedef signed int MxS32;
-#ifdef _MSC_VER
-typedef unsigned __int64 MxU64;
-typedef signed __int64 MxS64;
-#else
-typedef unsigned long long int MxU64;
-typedef signed long long int MxS64;
-#endif
+typedef uint64_t MxU64;
+typedef int64_t MxS64;
```
Comment (madebr) [inline LEGO1/omni/include/mxtypes.h:13]: This file also needs a bunch of static asserts.

File: LEGO1/lego/sources/misc/legotypes.h (hunk 2 above)
Comment (AJenbo) [reply LEGO1/lego/sources/misc/legotypes.h:41]: I added them under each type to make it easier to see what failed and that all of them are covered, and to make my life easier when adding them.
